name: Builds and tests with nix

on:
   push:
      branches: [ master ]
   pull_request:
      branches: [ master ]

jobs:
   nix:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: cachix/install-nix-action@v16
           with:
              nix_path: nixpkgs=channel:nixos-unstable
         # installed binaries would be in result/ if needed
         - name: box86-gnu32
           run: nix-build -A box86-gnu32
         - name: box86-armv7a-android
           run: nix-build -A box86-armv7a-android
